name: MyAuth
main: com.haniokasai.nukkit.MyAuth.Main
version: 1.0.0
api: [1.0.0]
load: POSTWORLD
author: haniokasai
description: Nukkit auth plugin (support ClientID)
commands:
 register:
  description: register your account
  usage: /register <password>
  permission: MyAuth.register
  default: true
 login:
  description: Login to your account
  usage: /login <password>
  permission: MyAuth.login
  default: true
 unregister:
  description: Reset Passwd(only from console)
  usage: /unregister <playername>
  permission: MyAuth.unregister
  default: op